# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 14:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task', '0004_auto_20170523_1619'),
        ('users', '0002_auto_20170523_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_in_standings', models.BooleanField()),
                ('code', models.FileField(upload_to='')),
                ('time', models.DateTimeField()),
                ('comment', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
        ),
        migrations.CreateModel(
            name='SolutionLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SolutionVerdict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name2', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='solution',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solution.SolutionLanguage'),
        ),
        migrations.AddField(
            model_name='solution',
            name='problem_modification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.ProblemModification'),
        ),
        migrations.AddField(
            model_name='solution',
            name='verdict',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solution.SolutionVerdict'),
        ),
    ]
