# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_auto_20170522_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
