# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 17:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contest', '0002_auto_20170522_2124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.BinaryField()),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AttachmentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProblemModification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('prefix', models.CharField(max_length=200)),
                ('comment', models.TextField()),
                ('archive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.Archive')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.Problem')),
            ],
        ),
        migrations.AddField(
            model_name='attachment',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.Problem'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='problem_modification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.ProblemModification'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.AttachmentType'),
        ),
    ]
