# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='contents',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='attachmenttype',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='problem',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='problemmodification',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='problemmodification',
            name='prefix',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
