# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 12:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20170522_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='problem',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='task.Problem'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='problem_modification',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='task.ProblemModification'),
        ),
    ]
