# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 20:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_auto_20170523_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TagProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('problem', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='task.Problem')),
            ],
        ),
        migrations.AlterField(
            model_name='problemmodification',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modification', to='task.Problem'),
        ),
        migrations.AddField(
            model_name='tagproblem',
            name='problem_modification',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='task.ProblemModification'),
        ),
        migrations.AddField(
            model_name='tagproblem',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.Tag'),
        ),
        migrations.AddField(
            model_name='tag',
            name='problem',
            field=models.ManyToManyField(blank=True, through='task.TagProblem', to='task.Problem'),
        ),
        migrations.AddField(
            model_name='tag',
            name='problem_modification',
            field=models.ManyToManyField(blank=True, through='task.TagProblem', to='task.ProblemModification'),
        ),
    ]
